travis:
  secure:
    BINSTAR_TOKEN: LUcqbs0WQ7e8n0Ub5EINnuLjtJEsr+2lx+6ObzfUwSmRwbsChMKtRQPlZ9Z7O/tpAoiL9z+sj6JK30ZwiJZ/STnhdHg65HLHkluUUfrr4Ki5OMHkC75CMcmNhO2C7LJKjmYh6G0ie2J4S9JZZ0DezL1PQWKKXg4LihUAK/8zSpvtuPd9EfRplB0ycwQ0QNHrwy6q0iSzx+JVXVBxfeo4coGgC482MCf5QCUsuxbMAxYxcbDGzfVpvaGfjIN8uEMPsh29efh4/RGoTth+s5jZL0BZcpX4pxM9PBjfUKm8BHsglf30OEGAonIIarH8JLIFpddlwgxSU3eKRpmVdsyITmsKmwQ2wal9JzCJrNJ807WGsS4ojETbErRGqItqhfpxuFt5N0ZifZB3FRBdKn8a7MAouseqToPZuesl29gzxOzhXyf8ZZxhBYdHzOFyfeCYOioIYxCYBDupldBmgLdUgoS5elfG5m6nWO+YCxnVerq2bOnaETLYi0J0EtEpwn57uAYWzwzxN9sAHgmjIVXKJQRNeq4M3r6MbXy4jrPWMo3Uuz0AhOXKHBsvKbxS3XQu9QLaluUEaWrCTllmYgbtZ6KHOc1X9H2bM098iNXjGr/nzW8YFy+0/kC2LzUhv0VJWsVZB8VByU+tMgnGnEVdzbypFEBTIePZlXb2zybRioc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
